// hasfilm/src/components/sections/gallery/GalleryGroup.tsx
import React, { useRef } from 'react';
import { useFrame, useThree } from '@react-three/fiber';
import { useScroll, Sparkles } from '@react-three/drei';
import * as THREE from 'three';
import { TIMELINE, SCENE_CONFIG, CAMERA_CONFIG } from '../../../config';
import { GALLERY_CONTENT } from '../../../data';
import ThickPanel from './ThickPanel';
import GalleryEffects from './GalleryEffects';
import { useGalleryColors, tintFogColor } from '../../../hooks/useGalleryColors';

/**
 * GalleryGroup - Cylindrical gallery with rotating curved panels.
 * Visible during the final phase of scroll (GALLERY_START - END).
 * The last panel disintegrates from left → right when scrolled past.
 */
const GalleryGroup: React.FC = () => {
    const scroll = useScroll();
    const groupRef = useRef<THREE.Group>(null);
    const backgroundRef = useRef<THREE.Group>(null); // Ref for Parallax Layer
    const { camera, scene } = useThree();

    // Performance: Only render heavy effects when in/near gallery section
    const [isActive, setIsActive] = React.useState(false);

    // Physics state for inertia/momentum (initialized to 0.2 to match transition end)
    const smoothedRot = useRef(0.2);

    // Dissolve progress refs (0 = visible, 1 = fully dissolved)
    const dissolveProgressRef = useRef(0);       // last panel
    const dissolveProgressRef2 = useRef(0);      // second-to-last panel (delayed)

    // === AMBIENT COLOR SYSTEM ===
    const galleryColors = useGalleryColors();
    const pointLightRef = useRef<THREE.PointLight>(null);
    const ambientLightRef = useRef<THREE.PointLight>(null);
    const glowMaterialRef = useRef<THREE.MeshBasicMaterial>(null);
    const currentAmbientColor = useRef(new THREE.Color(0.4, 0.4, 1.0));
    const currentFogColor = useRef(new THREE.Color('#050505'));

    // Add Atmospheric Haze (Fog)
    React.useEffect(() => {
        const oldFog = scene.fog;
        scene.fog = new THREE.FogExp2('#050505', 0.012);
        return () => {
            scene.fog = oldFog;
        };
    }, [scene]);

    const CAM_POS_START = new THREE.Vector3(
        CAMERA_CONFIG.START.x,
        CAMERA_CONFIG.START.y,
        CAMERA_CONFIG.START.z
    );
    const CAM_POS_END = new THREE.Vector3(
        CAMERA_CONFIG.END.x,
        CAMERA_CONFIG.END.y,
        CAMERA_CONFIG.END.z
    );

    // === Helper: Update ambient color system ===
    function updateAmbientColors(rawIndex: number, totalItems: number) {
        const colorIndex = Math.max(0, Math.min(Math.round(rawIndex), totalItems - 1));
        const targetColor = galleryColors[colorIndex];
        if (!targetColor) return;

        const dampFactor = 1 - Math.exp(-2.5 * (1 / 60));
        currentAmbientColor.current.lerp(targetColor, dampFactor);

        if (pointLightRef.current) {
            pointLightRef.current.color.copy(currentAmbientColor.current);
        }
        if (ambientLightRef.current) {
            ambientLightRef.current.color.copy(currentAmbientColor.current);
        }
        if (scene.fog && scene.fog instanceof THREE.FogExp2) {
            const targetFog = tintFogColor(currentAmbientColor.current, 0.12);
            currentFogColor.current.lerp(targetFog, dampFactor);
            scene.fog.color.copy(currentFogColor.current);
        }
        if (glowMaterialRef.current) {
            glowMaterialRef.current.color.copy(currentAmbientColor.current);
        }
    }

    useFrame(() => {
        const r = scroll.offset;

        // Manage active state for performance — only render heavy effects
        // during the actual gallery zone, not before (About section) or after (Highlights)
        const shouldBeActive = r > TIMELINE.ABOUT_STAY && r <= 0.876;

        if (isActive !== shouldBeActive) {
            setIsActive(shouldBeActive);
        }

        if (!groupRef.current) return;

        // Hide immediately after dissolve completes (0.875) — no reason to
        // keep 3D gallery visible after panels are dissolved and camera is
        // zoomed to z=35. Leaving it on causes the "behind gallery" feeling
        // as the WebGL canvas shows the back of the cylinder.
        const POST_DISSOLVE_HIDE = 0.876;

        // Zero out fog once past the gallery to prevent haze over Highlights
        if (scene.fog && scene.fog instanceof THREE.FogExp2) {
            if (r > POST_DISSOLVE_HIDE) {
                scene.fog.density = 0;
            } else if (r >= TIMELINE.ABOUT_STAY) {
                // Restore fog during active gallery zone
                scene.fog.density = 0.012;
            }
        }

        if (r < TIMELINE.ABOUT_STAY || r > POST_DISSOLVE_HIDE) {
            groupRef.current.visible = false;
            return;
        }

        groupRef.current.visible = true;

        // TRANSITION phase
        if (r >= TIMELINE.ABOUT_STAY && r < TIMELINE.GALLERY_START) {
            const t = (r - TIMELINE.ABOUT_STAY) / (TIMELINE.GALLERY_START - TIMELINE.ABOUT_STAY);
            const smoothT = t * t * (3 - 2 * t);

            camera.position.lerpVectors(CAM_POS_START, CAM_POS_END, smoothT);

            const scale = THREE.MathUtils.lerp(0.8, 1, smoothT);
            groupRef.current.scale.setScalar(scale);

            const transitionRot = smoothT * 0.2;
            groupRef.current.rotation.y = transitionRot;

            smoothedRot.current = transitionRot;
        }
        // ACTIVE gallery phase — split into: Viewing → Pause → Dissolve
        else if (r >= TIMELINE.GALLERY_START) {
            camera.position.copy(CAM_POS_END);
            groupRef.current.scale.setScalar(1);

            const totalItems = GALLERY_CONTENT.length;
            const angleStep = SCENE_CONFIG.CYLINDER_ARC / totalItems;

            // ── Sub-phase boundaries ──
            const GALLERY_VIEW_END = 0.85;   // Gallery sticky scroll ends
            const DISSOLVE_START = 0.855;    // Dissolve begins (after HUD fade pause)
            const DISSOLVE_END = 0.875;      // Dissolve complete → screen dark

            if (r < GALLERY_VIEW_END) {
                // ── SUB-PHASE A: Sticky scroll through panels ──
                const rotProgress = (r - TIMELINE.GALLERY_START) / (GALLERY_VIEW_END - TIMELINE.GALLERY_START);

                const rawIndex = Math.max(0, Math.min(rotProgress * totalItems - 0.5, totalItems - 1));
                const index = Math.min(Math.floor(rawIndex), totalItems - 2);
                let frac = index >= 0 ? rawIndex - index : 0;

                if (rawIndex >= totalItems - 1) { frac = 0; }

                // Sticky easing
                if (frac < 0.5) {
                    frac = 4 * frac * frac * frac;
                } else {
                    frac = 1 - Math.pow(-2 * frac + 2, 3) / 2;
                }

                const stickyIndex = rawIndex >= totalItems - 1 ? totalItems - 1 : index + frac;
                const stickyRot = 0.2 + (stickyIndex * angleStep);

                smoothedRot.current = THREE.MathUtils.damp(smoothedRot.current, stickyRot, 5, 1 / 60);
                groupRef.current.rotation.y = smoothedRot.current;

                // PARALLAX
                if (backgroundRef.current) {
                    backgroundRef.current.rotation.y = smoothedRot.current * 0.25;
                }

                dissolveProgressRef.current = 0;
                dissolveProgressRef2.current = 0;
                updateAmbientColors(rawIndex, totalItems);

            } else if (r < DISSOLVE_START) {
                // ── SUB-PHASE B: Pause — last panel dwells, HUD fades ──
                const lastPanelRot = 0.2 + ((totalItems - 1) * angleStep);
                smoothedRot.current = THREE.MathUtils.damp(smoothedRot.current, lastPanelRot, 5, 1 / 60);
                groupRef.current.rotation.y = smoothedRot.current;

                dissolveProgressRef.current = 0;
                dissolveProgressRef2.current = 0;
                updateAmbientColors(totalItems - 1, totalItems);

            } else if (r < DISSOLVE_END) {
                // ── SUB-PHASE C: Dissolve + Zoom (slow→fast) ──
                const lastPanelRot = 0.2 + ((totalItems - 1) * angleStep);
                smoothedRot.current = THREE.MathUtils.damp(smoothedRot.current, lastPanelRot, 5, 1 / 60);
                groupRef.current.rotation.y = smoothedRot.current;

                // Dissolve progress: 0 → 1
                const dissolveT = (r - DISSOLVE_START) / (DISSOLVE_END - DISSOLVE_START);
                const clampedT = Math.max(0, Math.min(1, dissolveT));
                const eased = clampedT < 0.5
                    ? 2 * clampedT * clampedT
                    : 1 - Math.pow(-2 * clampedT + 2, 2) / 2;
                dissolveProgressRef.current = eased;

                // Second-to-last panel: delayed, caps at ~40%
                const delay2 = 0.35;
                const raw2 = Math.max(0, (clampedT - delay2) / (1 - delay2));
                dissolveProgressRef2.current = Math.min(0.4, raw2 * 0.6);

                // Camera zoom: SLOW first half, then RAPID acceleration
                // Using exponential curve: t^3 gives slow start, fast finish
                const zoomT = clampedT * clampedT * clampedT;
                const targetZ = THREE.MathUtils.lerp(CAM_POS_END.z, 35, zoomT);
                camera.position.set(CAM_POS_END.x, CAM_POS_END.y, targetZ);

                updateAmbientColors(totalItems - 1, totalItems);

            } else {
                // ── SUB-PHASE D: Post-dissolve — gallery fully dissolved, camera locked ──
                const lastPanelRot = 0.2 + ((totalItems - 1) * angleStep);
                smoothedRot.current = THREE.MathUtils.damp(smoothedRot.current, lastPanelRot, 5, 1 / 60);
                groupRef.current.rotation.y = smoothedRot.current;

                dissolveProgressRef.current = 1;
                dissolveProgressRef2.current = 0.4;
                camera.position.set(CAM_POS_END.x, CAM_POS_END.y, 35);

                updateAmbientColors(totalItems - 1, totalItems);
            }
        }

        camera.lookAt(0, 0, 0);
    });

    const lastIndex = GALLERY_CONTENT.length - 1;
    const secondLastIndex = GALLERY_CONTENT.length - 2;

    return (
        <>
            <group ref={groupRef} position={[0, 0, 0]}>
                {GALLERY_CONTENT.map((item, i) => {
                    // Determine which dissolve ref to pass
                    let panelDissolveRef: React.RefObject<number> | undefined;
                    if (i === lastIndex) panelDissolveRef = dissolveProgressRef;
                    else if (i === secondLastIndex) panelDissolveRef = dissolveProgressRef2;

                    return (
                        <ThickPanel
                            key={i}
                            url={item.url}
                            index={i}
                            total={GALLERY_CONTENT.length}
                            radius={SCENE_CONFIG.CYLINDER_RADIUS}
                            gap={0.008}
                            thickness={2}
                            dissolveProgressRef={panelDissolveRef}
                        />
                    );
                })}

                {/* Inner Glow - Dynamic ambient color from focused image */}
                <pointLight ref={pointLightRef} position={[0, 0, 0]} intensity={3} color="#6666ff" distance={25} />

                {/* Secondary Ambient Fill Light - wider, softer spread */}
                <pointLight ref={ambientLightRef} position={[0, 5, 0]} intensity={1.5} color="#6666ff" distance={60} />

                {/* Ambient Glow Sphere - subtle volumetric color wash */}
                <mesh>
                    <sphereGeometry args={[SCENE_CONFIG.CYLINDER_RADIUS * 0.75, 32, 32]} />
                    <meshBasicMaterial
                        ref={glowMaterialRef}
                        color="#6666ff"
                        transparent
                        opacity={0.025}
                        side={THREE.BackSide}
                    />
                </mesh>

                {/* HEAVY EFFECTS - Only mount when near gallery to save Hero performance */}
                {isActive && (
                    <>
                        {/* PARALLAX LAYER: Floating Dust / Sparkles */}
                        <group ref={backgroundRef}>
                            <Sparkles
                                count={200}
                                scale={[SCENE_CONFIG.CYLINDER_RADIUS * 1.5, SCENE_CONFIG.CYLINDER_HEIGHT, SCENE_CONFIG.CYLINDER_RADIUS * 1.5]}
                                size={4}
                                speed={0.4}
                                opacity={0.5}
                                color="#ffffff"
                            />
                        </group>

                        <GalleryEffects />

                        {/* Reflection Occluder - Blocks the view of the back-side reflections */}
                        <mesh position={[0, -SCENE_CONFIG.CYLINDER_HEIGHT - 0.2, 0]}>
                            <cylinderGeometry args={[SCENE_CONFIG.CYLINDER_RADIUS - 0.1, SCENE_CONFIG.CYLINDER_RADIUS - 0.1, SCENE_CONFIG.CYLINDER_HEIGHT, 64, 1, true]} />
                            <meshBasicMaterial color="#000000" side={THREE.DoubleSide} />
                        </mesh>
                    </>
                )}
            </group>
        </>
    );
};

export default GalleryGroup;

// src/lib/components/3d/GalleryGroup.svelte
<script lang="ts">
    import { T, useTask, useThrelte } from "@threlte/core";
    import {
        Group,
        Color,
        FogExp2,
        MeshBasicMaterial,
        MathUtils,
        BackSide,
        type PointLight,
    } from "three";
    import { onMount } from "svelte";
    import { scrollState } from "$lib/state/scrollState.svelte";
    import { GALLERY_CONTENT } from "$lib/data/gallery";
    import ThickPanel from "./ThickPanel.svelte";
    import { clamp } from "$lib/utils/easing";

    // ============================================================================
    // CONFIGURATION
    // ============================================================================

    const CYLINDER_RADIUS = 50;
    const CYLINDER_HEIGHT = 12;
    const CYLINDER_ARC = Math.PI * 0.8;
    const GALLERY_START_ROTATION = 0.2;

    // Scroll progress ranges (within our 1000dvh page)
    // Gallery section is at ~30-50% progress (200dvh out of 1000dvh)
    const GALLERY_ZONE_START = 0.3; // Where gallery section begins
    const TRANSITION_END = 0.34; // Camera arrives at viewing position
    const VIEW_START = 0.34; // Panel viewing begins
    const VIEW_END = 0.46; // Last panel reached
    const DISSOLVE_START = 0.47; // Dissolve begins
    const DISSOLVE_END = 0.49; // Dissolve complete
    const PULLBACK_START = 0.49; // Camera begins pulling back
    const PULLBACK_END = 0.54; // Gallery fully faded out

    // Camera positions
    const CAM_START = { x: 0, y: 0, z: 0 };
    const CAM_END = { x: 0, y: -2, z: 60 };

    // ============================================================================
    // STATE
    // ============================================================================

    const totalItems = GALLERY_CONTENT.length;
    const angleStep = CYLINDER_ARC / totalItems;

    let groupRef: Group | undefined = $state();
    let pointLightRef: PointLight | undefined = $state();
    let ambientLightRef: PointLight | undefined = $state();
    let glowMaterialRef: MeshBasicMaterial | undefined = $state();

    let smoothedRot = GALLERY_START_ROTATION;
    let dissolveProgress1 = $state(0); // last panel
    let dissolveProgress2 = $state(0); // second-to-last panel
    let isVisible = $state(false);
    let currentPanelIndex = $state(0);

    // Ambient color system
    const dominantColors = GALLERY_CONTENT.map(
        (item) => new Color(item.dominantColor),
    );
    const currentAmbientColor = new Color(0.4, 0.4, 1.0);
    const currentFogColor = new Color("#050505");

    // ============================================================================
    // HELPERS
    // ============================================================================

    const { scene, camera, invalidate } = useThrelte();

    function smoothstep(t: number): number {
        return t * t * (3 - 2 * t);
    }

    function updateAmbientColors(rawIndex: number) {
        const colorIndex = Math.max(
            0,
            Math.min(Math.round(rawIndex), totalItems - 1),
        );
        const targetColor = dominantColors[colorIndex];
        if (!targetColor) return;

        const dampFactor = 1 - Math.exp(-2.5 * (1 / 60));
        currentAmbientColor.lerp(targetColor, dampFactor);

        if (pointLightRef) {
            pointLightRef.color.copy(currentAmbientColor);
        }
        if (ambientLightRef) {
            ambientLightRef.color.copy(currentAmbientColor);
        }

        // Tint fog with ambient color
        if (scene.fog && scene.fog instanceof FogExp2) {
            const base = new Color("#050505");
            const tinted = base.clone().lerp(currentAmbientColor, 0.12);
            currentFogColor.lerp(tinted, dampFactor);
            scene.fog.color.copy(currentFogColor);
        }

        if (glowMaterialRef) {
            glowMaterialRef.color.copy(currentAmbientColor);
        }
    }

    // ============================================================================
    // PER-FRAME UPDATE
    // ============================================================================

    useTask(() => {
        const r = scrollState.progress;

        // Visibility check
        const shouldBeVisible =
            r >= GALLERY_ZONE_START - 0.02 && r < PULLBACK_END;
        isVisible = shouldBeVisible;
        if (!isVisible || !groupRef) return;

        // Set fog
        if (scene.fog && scene.fog instanceof FogExp2) {
            if (r > PULLBACK_END - 0.01) {
                scene.fog.density = 0;
            } else if (r >= GALLERY_ZONE_START) {
                scene.fog.density = 0.012;
            }
        }

        // ── TRANSITION PHASE: Camera flies to viewing position ──
        if (r >= GALLERY_ZONE_START && r < TRANSITION_END) {
            const t =
                (r - GALLERY_ZONE_START) /
                (TRANSITION_END - GALLERY_ZONE_START);
            const eased = smoothstep(clamp(t, 0, 1));

            camera.current.position.set(
                MathUtils.lerp(CAM_START.x, CAM_END.x, eased),
                MathUtils.lerp(CAM_START.y, CAM_END.y, eased),
                MathUtils.lerp(CAM_START.z, CAM_END.z, eased),
            );

            const scale = MathUtils.lerp(0.8, 1, eased);
            groupRef.scale.setScalar(scale);

            const transitionRot = eased * GALLERY_START_ROTATION;
            groupRef.rotation.y = transitionRot;
            smoothedRot = transitionRot;

            dissolveProgress1 = 0;
            dissolveProgress2 = 0;

            // Ensure canvas is fully visible during entry
            scrollState.galleryCanvasOpacity = 1;

            if (pointLightRef) pointLightRef.intensity = 3;
            if (ambientLightRef) ambientLightRef.intensity = 1.5;

            currentPanelIndex = 0;
        }
        // ── VIEWING PHASE: Rotate through panels ──
        else if (r >= VIEW_START && r < VIEW_END) {
            camera.current.position.set(CAM_END.x, CAM_END.y, CAM_END.z);
            groupRef.scale.setScalar(1);

            const rotProgress = (r - VIEW_START) / (VIEW_END - VIEW_START);
            const rawIndex = Math.max(
                0,
                Math.min(rotProgress * totalItems - 0.5, totalItems - 1),
            );
            const snapIndex = Math.min(Math.floor(rawIndex), totalItems - 2);
            let frac = snapIndex >= 0 ? rawIndex - snapIndex : 0;

            if (rawIndex >= totalItems - 1) frac = 0;

            // Sticky cubic easing
            if (frac < 0.5) {
                frac = 4 * frac * frac * frac;
            } else {
                frac = 1 - Math.pow(-2 * frac + 2, 3) / 2;
            }

            const stickyIndex =
                rawIndex >= totalItems - 1 ? totalItems - 1 : snapIndex + frac;
            const stickyRot = GALLERY_START_ROTATION + stickyIndex * angleStep;

            smoothedRot = MathUtils.damp(smoothedRot, stickyRot, 5, 1 / 60);
            groupRef.rotation.y = smoothedRot;

            dissolveProgress1 = 0;
            dissolveProgress2 = 0;

            if (pointLightRef) pointLightRef.intensity = 3;
            if (ambientLightRef) ambientLightRef.intensity = 1.5;

            currentPanelIndex = Math.round(rawIndex);
            updateAmbientColors(rawIndex);
        }
        // ── PAUSE PHASE: Last panel dwells ──
        else if (r >= VIEW_END && r < DISSOLVE_START) {
            const lastPanelRot =
                GALLERY_START_ROTATION + (totalItems - 1) * angleStep;
            smoothedRot = MathUtils.damp(smoothedRot, lastPanelRot, 5, 1 / 60);
            groupRef.rotation.y = smoothedRot;

            dissolveProgress1 = 0;
            dissolveProgress2 = 0;

            if (pointLightRef) pointLightRef.intensity = 3;
            if (ambientLightRef) ambientLightRef.intensity = 1.5;

            currentPanelIndex = totalItems - 1;
            updateAmbientColors(totalItems - 1);
        }
        // ── DISSOLVE PHASE ──
        else if (r >= DISSOLVE_START && r < DISSOLVE_END) {
            const lastPanelRot =
                GALLERY_START_ROTATION + (totalItems - 1) * angleStep;
            smoothedRot = MathUtils.damp(smoothedRot, lastPanelRot, 5, 1 / 60);
            groupRef.rotation.y = smoothedRot;

            const dissolveT = clamp(
                (r - DISSOLVE_START) / (DISSOLVE_END - DISSOLVE_START),
                0,
                1,
            );
            const eased =
                dissolveT < 0.5
                    ? 2 * dissolveT * dissolveT
                    : 1 - Math.pow(-2 * dissolveT + 2, 2) / 2;

            dissolveProgress1 = eased;

            // Second-to-last: delayed, caps at ~40%
            const delay2 = 0.35;
            const raw2 = Math.max(0, (dissolveT - delay2) / (1 - delay2));
            dissolveProgress2 = Math.min(0.4, raw2 * 0.6);

            // Camera zoom toward panels
            const zoomT = dissolveT * dissolveT * dissolveT;
            const targetZ = MathUtils.lerp(CAM_END.z, 50, zoomT);
            camera.current.position.set(CAM_END.x, CAM_END.y, targetZ);

            // Fade lights
            const lightFade = dissolveT * dissolveT * dissolveT;
            if (pointLightRef)
                pointLightRef.intensity = MathUtils.lerp(3, 0, lightFade);
            if (ambientLightRef)
                ambientLightRef.intensity = MathUtils.lerp(1.5, 0, lightFade);

            currentPanelIndex = totalItems - 1;
            updateAmbientColors(totalItems - 1);
        }
        // ── PULLBACK PHASE: Camera retreats + canvas fades ──
        else if (r >= PULLBACK_START && r < PULLBACK_END) {
            dissolveProgress1 = 1;
            dissolveProgress2 = 0.4;

            const pullT = clamp(
                (r - PULLBACK_START) / (PULLBACK_END - PULLBACK_START),
                0,
                1,
            );
            const easedPull = smoothstep(pullT);

            // Camera pulls back from z=50 → z=80
            const pullZ = MathUtils.lerp(50, 80, easedPull);
            camera.current.position.set(CAM_END.x, CAM_END.y, pullZ);

            // Canvas fades out
            scrollState.galleryCanvasOpacity = 1 - easedPull;

            if (pointLightRef) pointLightRef.intensity = 0;
            if (ambientLightRef) ambientLightRef.intensity = 0;
        }
        // ── FULLY HIDDEN ──
        else if (r >= PULLBACK_END) {
            dissolveProgress1 = 1;
            dissolveProgress2 = 0.4;
            scrollState.galleryCanvasOpacity = 0;

            camera.current.position.set(CAM_END.x, CAM_END.y, 80);
            if (pointLightRef) pointLightRef.intensity = 0;
            if (ambientLightRef) ambientLightRef.intensity = 0;
        }

        camera.current.lookAt(0, 0, 0);
        invalidate();
    });
</script>

{#if isVisible}
    <T.Group bind:ref={groupRef}>
        <!-- Gallery Panels -->
        {#each GALLERY_CONTENT as item, i}
            <ThickPanel
                url={item.url}
                index={i}
                total={totalItems}
                radius={CYLINDER_RADIUS}
                arc={CYLINDER_ARC}
                height={CYLINDER_HEIGHT}
                dissolveProgress={i === totalItems - 1
                    ? dissolveProgress1
                    : i === totalItems - 2
                      ? dissolveProgress2
                      : 0}
            />
        {/each}

        <!-- Inner Glow — Dynamic ambient color from focused image -->
        <T.PointLight
            bind:ref={pointLightRef}
            position={[0, 0, 0]}
            intensity={3}
            color="#6666ff"
            distance={25}
        />

        <!-- Secondary Ambient Fill Light -->
        <T.PointLight
            bind:ref={ambientLightRef}
            position={[0, 5, 0]}
            intensity={1.5}
            color="#6666ff"
            distance={60}
        />

        <!-- Ambient Glow Sphere -->
        <T.Mesh>
            <T.SphereGeometry args={[CYLINDER_RADIUS * 0.75, 32, 32]} />
            <T.MeshBasicMaterial
                bind:ref={glowMaterialRef}
                color="#6666ff"
                transparent
                opacity={0.025}
                side={BackSide}
            />
        </T.Mesh>

        <!-- Reflection Occluder -->
        <T.Mesh position.y={-CYLINDER_HEIGHT - 0.2}>
            <T.CylinderGeometry
                args={[
                    CYLINDER_RADIUS - 0.1,
                    CYLINDER_RADIUS - 0.1,
                    CYLINDER_HEIGHT,
                    64,
                    1,
                    true,
                ]}
            />
            <T.MeshBasicMaterial color="#000000" side={2} />
        </T.Mesh>
    </T.Group>
{/if}
